### ISSUE TITLE
quickcheck timeout

### ISSUE THREAD

**Issue by bergmark** [phadej/spdx#8] opened 2016-07-25 19:59 UTC
The test-suite took longer than 10 minutes to run, is it looping?

```
> /tmp/stackage-build8/spdx-0.2.1.0$ dist/build/test/test
Tests
  Properties
    By Quickcheck
      licence identifiers are valid licenses:           OK (0.01s)
        +++ OK, passed 100 tests.
      satisfies osi checked:                            
```

**Comment by phadej** [comment] 2016-07-25 20:00
sometimes QuickCheck generates very ill-behaving example. Or does this happening every time?

**Comment by bergmark** [comment] 2016-07-25 20:06
I assume it's the only time it has happened since spdx is in nightly already.

**Comment by phadej** [comment] 2016-07-25 20:11
Then I'll close this. `spdx` has been in stackage for an year now. Hopefully this happens only once a year or even less.

I'll make test be verbose, so will see on which kind of example the function miss-behaves.

Will close after that's done.

**Comment by phadej** [comment] 2018-10-29 10:46
Released https://hackage.haskell.org/package/spdx-1, cannot reproduce anymore

**Closed as completed by phadej** 2018-10-29 10:46 UTC
