### ISSUE TITLE
Test failure on LicenseExpression

### ISSUE THREAD

**Issue by felixonmars** [phadej/spdx#25] opened 2021-06-20 02:20 UTC
```
        LicenseExpression:                              FAIL
          *** Failed! Falsified (after 14 tests and 2 shrinks):
          License (ELicense (ELicenseId BSD_2_Clause_NetBSD) Nothing)
          BSD-2-Clause-NetBSD
          "<eitherParsec>" (line 1, column 20):
          unexpected Unknown SPDX license identifier: 'BSD-2-Clause-NetBSD'  /      = License (ELicense (ELicenseId BSD_2_Clause_NetBSD) Nothing)
          Use --quickcheck-replay=258595 to reproduce.
```

**Comment by phadej** [comment] 2021-06-20 10:28
which GHC version (or `Cabal` dependency) version you compile with. Which version of `spdx`? I cannot reproduce.

**Comment by phadej** [comment] 2021-06-20 10:46
Probably fixed by https://github.com/phadej/spdx/commit/8afaa090a5f52a9dbde057b79ccf9739bcef8812, I will not make release because of tests only.

**Closed as completed by phadej** 2021-06-20 10:46 UTC
